### PR TITLE
Make PTMCMCSampler Python 3 Compatible

### PR DESCRIPTION
**Pull request by Hazboun6**
I went through and changed all the calls to print to have (), even those that are commented out. (I did not change as many lines as the comparison of the files shows, only the calls to print.)

Also, changed a call to `numpy.unique`, since `sort()` command no longer works with functions in Python 3. Used `numpy.array(list(set()))` instead. 

Added print_function and 'absolute_importto the imports fromfuture. Should not affect the sampling since division was already imported.

These imports should make it fully backwards compatible.

Testing: It loads properly and samples.

### CODE REVIEW

**Comment by jellis18** [comment]
Have you checked that this still works in Python2.7?

**Comment by Hazboun6** [comment]
I just did a full PAL2 test of PTMCMCSampler in my Python2.7 environment. Looks like it is working great. Happy to share any tests if you want to see something.

**Comment by Hazboun6** [comment]
Made one more small change

**Comment by Hazboun6** [comment]
Made one more change to an import call. For the test above. All of these tests pass so far.

**Pull request merged**
